version: '3.7'
services:

  app:
    build:
      context: ./docker/
      dockerfile: app.dockerfile
    image: app-chalenge-contacts
    container_name: chalenge-contacts-app
    tty: true
    working_dir: /var/www
    volumes:
      - ./src/:/var/www
    environment:
      DB_PORT: 3306
      DB_HOST: database
      TZ: 'America/Sao_Paulo'
      PHP_REDIS_SESSION_HOST: 'redis'
      CREATE_LARAVEL_STORAGE: '1'
    networks:
      - _net
    ports:
      - 9000:9000
      # - 9001:9001

  web:
    build:
      context: ./docker/
      dockerfile: web.dockerfile
    image: web-chalenge-contacts
    container_name: chalenge-contacts-web
    tty: true
    working_dir: /var/www
    depends_on:
      - app
    ports:
      - 80:80
    networks:
      - _net

  database:
    build:
      context: ./docker/
      dockerfile: db.dockerfile
    image: database-chalenge-contacts
    container_name: chalenge-contacts-database
    tty: true
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - 3306:3306
    networks:
      - _net

  redis:
    build:
      context: ./docker/
      dockerfile: redis.dockerfile
    image: redis-chalenge-contacts
    container_name: redis-contacts-database
    ports:
      - "6379:6379"
    networks:
      - _net

volumes:
  dbdata:
    driver: local
networks:
  _net:
    driver: "bridge"
